# ./docker-compose.yml

version: '3'

services:
  memcached:
    image: memcached:1.4
    ports:
      - "11212:11211"
  api:
    environment:
            - APPLICATION_ENV=beta
    image: surfingdirt/rest-api:3
    container_name: api
    volumes:
      - /home/mikael/www/beta/api/:/var/www/html/
    ports:
      - "8006:80"
    stdin_open: true
    tty: true