# ./docker-compose.beta.yml

version: '3'

services:
  zipkin:
    container_name: zipkin_beta
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9412"
  memcached:
    image: memcached:1.4
    container_name: memcached_beta
    ports:
      - "11213:11211"
  api:
    environment:
            - APPLICATION_ENV=beta
    image: surfingdirt/rest-api:5
    container_name: api_beta
    volumes:
      - /home/mikael/www/beta/api/:/var/www/html/
    ports:
      - "8006:80"
    stdin_open: true
    tty: true