# ./docker-compose.beta.yml

version: '3'

services:
  memcached_beta:
    image: memcached:1.4
    container_name: memcached_beta
    ports:
      - "11213:11211"
  api_beta:
    environment:
            - APPLICATION_ENV=beta
    image: surfingdirt/rest-api:3
    container_name: api_beta
    volumes:
      - /home/mikael/www/beta/api/:/var/www/html/
    ports:
      - "8006:80"
    stdin_open: true
    tty: true