<?php
/*
 * After much flip-flopping on how to best handle security, here's the decision:
 * - the API does not escape anything because it's too early to do it at that level (1)
 * - it's up to the clients to escape data
 * - React auto-escapes everything unless you choose to shoot yourself in the foot with dangerouslySetInnerHTML
 * - on the client app's node server, when inlining the Apollo state JSON data, make sure to do this (2):
 *  window.__APOLLO_STATE__ = JSON.stringify(client.extract()).replace(/</g, '\\u003c');
 *
 * (1) https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/preventing_xss/preventing_xss.html#philosophy-and-general-rules
 * (2) https://github.com/apollographql/apollo-client/issues/5567
 */
echo json_encode($this->output);