<?php
/*
 * Because of limitations on the client, full-security around XSS hinges solely around the API removing dangerous chars
 *
 * We must escape <, >, &, and ". Why escape quotes? https://www.securitysift.com/quotes-and-xss-planning-your-escape/
 *
 * This is achieved by using json_encode with the poorly documented JSON_HEX_QUOT
 * $string = '{"a": "it cost 20&euros; and a </script><script>alert(\'xss\')</script>)"}';
 * echo json_encode($string, JSON_HEX_QUOT);
 * "{\u0022a\u0022: \u0022it cost 20&euros; and a <\/script><script>alert('xss')<\/script>)\u0022}"
 *
 */
echo json_encode($this->output, JSON_HEX_QUOT);